included:
  - wkwktodo/
excluded:
  - wkwktodo/App/AppDelegate.swift
  - wkwktodo/App/SceneDelegate.swift
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - unused_capture_list
  - force_cast
  - line_length
analyzer_rules:
  - unused_declaration
  - unused_import
